spring:
  profiles:
    active: fd-client

  rabbitmq:
    password: guest
    username: guest
    host: localhost
    port: 5672
    virtual-host: /

logging:
  level:
    org.flockdata: error
    configuration: info
    org.springframework: error
    org.jline: error

org.fd:
  client:
    # The API key is used to identify a user associated with the company.
    # You can get your APIKey via Curl with the following command
    # curl -u mike http://localhost:14001/api/v1/profiles/me

    # Either set in in your config file or pass it as a command line parameter
    # --org.fd.client.apikey=SDKMcCU_TRCh7fL09PoFUg
    # apikey: SDKMcCU_TRCh7fL09PoFUg
    batchsize: 1
    login:
      user: demo
    default:
      company: FlockData

  engine:
    api: http://localhost:14001


