version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.9
    command: "elasticsearch -E node.name=fd-dev -E cluster.name=fd-dev -E node.master=true -E discovery.type=single-node -E network.host=0.0.0.0 -E xpack.security.enabled=false"
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - fd-dev-es:/usr/share/elasticsearch/data
    expose:
      - 9200
      - 9300  
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.9
    expose:
      - 5601
      - 32776
    ports:
      - '5601:5601'
      - '32776:32776'

    environment:
      SERVER_NAME: kibana.localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200
      XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED: "false"
    
  rabbit:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    expose:
      - 15682
      - 5672

  riak:
    image: lapax/riak:latest
    ports:
      - '8087:8087'
      - '8098:8098'
    expose:
      - 8098
    environment:
      storage_backend: leveldb
      platform_data_dir: /data/riak

    volumes:
      - fd-dev-riak:/data/riak

volumes:
  fd-dev-es: {}
  fd-dev-riak: {}

