application:
  title: FlockData SearchWriter

eureka:
  client:
    serviceUrl:
      defaultZone: ${org.fd.discovery.url:http://127.0.0.1:8761/eureka/}
    enabled: 'false'

spring:
  application:
    name: fd-search
  profiles:
    active: fd-no-auth
    include: fd-server
  cloud:
    config:
      discovery:
        enabled: false
  messages:
    encoding: UTF-8
  http:
    encoding:
      charset: UTF-8 # the encoding of HTTP requests/responses
      enabled: 'true' # enable http encoding support
      force: 'true' # force the configured encoding

server:
  port: 8081

es:
  clustername: es_flockdata
  http:
    port: 9200
  tcp:
    port: 9300
  path:
    home: ./
    data: ../data/fd/es
  # , serparated list of hosts to connect to if transportOnly == true
  #nodes: 192.168.99.100:9300

rabbit:
    user: guest
    pass: guest
    host: localhost
    port: 5672
    heartbeat.secs: 30

org.fd:
  engine:
    api: http://localhost:8080
    messaging:
      queue: fd.engine.queue
      binding: fd.engine.binding
      exchange: fd.engine.exchange
      dlq:
        queue: fd.engine.dlq.queue
        exchange: fd.engine.dlq.exchange
      prefetchCount: 3
      concurrentConsumers: 2
    executor:
      poolSize: 4
      capacity: 4
  search:
    es:
      mappings: ./
      #Is the node going to be a client node which means it will hold no data ?
      # True for production/cluster
      # False for dev/demo (default)
      # transportOnly: true

      # A local node is a node that uses a local (JVM level) discovery and transport
      # True for dev/demo  (default)
      # False for production/cluster
      # local: false

    system:
      api: api
    messaging:
      exchange: fd.search.exchange
      binding: fd.search.binding
      queue: fd.search.queue
      dlq.queue: fd.search.dlq.queue
      dlq.exchange: fd.search.dlq.exchange
      concurrentConsumers: 2
      prefetchCount: 3
    executor:
      poolSize: 4
      capacity: 10



