application:
  title: FlockData SearchWriter

eureka:
  client:
    healthcheck:
      enabled: false
    serviceUrl:
      defaultZone: ${org.fd.discovery.url:http://127.0.0.1:8761/eureka/}
    enabled: false

spring:
  application:
    name: fd-search
  profiles:
    active: fd-no-auth
    include: fd-server
  cloud:
    discovery:
      enabled: false
  messages:
    encoding: UTF-8

server:
  port: 8081

es:
  clustername: es_flockdata
  # this clients ports
  http:
    port: 9200
  tcp:
    port: 9300

  path:
    home: ./
    data: ../data/fd/es


  # , serparated list of hosts to connect to if transportOnly == true
#  nodes: localhost:9300

rabbit:
    user: guest
    pass: guest
    host: localhost
    port: 5672
    heartbeat.secs: 30

org.fd:
  engine:
    api: http://localhost:8080
    messaging:
      queue: fd.engine.queue
      binding: fd.engine.binding
      exchange: fd.engine.exchange
      dlq:
        queue: fd.engine.dlq.queue
        exchange: fd.engine.dlq.exchange
      prefetchCount: 3
      concurrentConsumers: 2
    executor:
      poolSize: 4
      capacity: 4
  search:
    es:
      mappings: ./
      #Is the node going to be a client node which means it will hold no data ?
      # True for production/cluster
      # False for dev/demo (default)
      transportOnly: false

      # Look outside of this jvm for an ES host
      # True for dev/transportOnly = false (default)
      # False for production/cluster/remote es client
      local: true

    system:
      api: api
    messaging:
      exchange: fd.search.exchange
      binding: fd.search.binding
      queue: fd.search.queue
      dlq.queue: fd.search.dlq.queue
      dlq.exchange: fd.search.dlq.exchange
      concurrentConsumers: 2
      prefetchCount: 3
    executor:
      poolSize: 4
      capacity: 10



