application:
  title: FlockData SearchWriter

eureka:
  client:
    serviceUrl:
      defaultZone: ${org.fd.discovery.url:http://127.0.0.1:8761/eureka/}


spring:
  application:
    name: fd-search
  profiles:
    active: production
    include: fd-auth-test
  cloud:
    config:
      discovery:
        enabled: false


server:
  port: 8081



es:
  clustername: es_flockdata
  http:
    port: 9200
  tcp:
    port: 9300
  path:
    home: ./
    data: ${es.path.home}/data/es

rabbit:
    user: guest
    pass: guest
    host: localhost
    port: 5672
    heartbeat.secs: 30

org.fd:
  engine:
    api: http://localhost:8080/api
    messaging:
      queue: fd.engine.queue
      binding: fd.engine.binding
      exchange: fd.engine.exchange
      dlq:
        queue: fd.engine.dlq.queue
        exchange: fd.engine.dlq.exchange
      prefetchCount: 3
      concurrentConsumers: 2
    executor:
      poolSize: 4
      capacity: 4
  search:
    es:
      mappings: ./
    system:
      api: api
    messaging:
      exchange: fd.search.exchange
      binding: fd.search.binding
      queue: fd.search.queue
      dlq.queue: fd.search.dlq.queue
      dlq.exchange: fd.search.dlq.exchange
      concurrentConsumers: 2
      prefetchCount: 3
    executor:
      poolSize: 4
      capacity: 10



