version: 2
jobs:

  checkout-code:
    machine:
      enabled: true
    working_directory: '~/org.flockdata'
    steps:
      - checkout
      - save_cache:
          key: org-flockdata-src-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/org.flockdata

  build-common:
    machine:
      enabled: true
    environment:
      _JAVA_OPTIONS: "-Xms256m -Xmx512m"
    working_directory: '~/org.flockdata'
    # caches are immutable and will be built once by the common job
    steps:
      - restore_cache:
            key: org-flockdata-src-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
            key: org-flockdata-v2a-{{ checksum "pom.xml" }}

      - run:
          command: 'rm -rf ~/.m2/repository/org/flockdata'

      - run:
          command: 'mvn clean install -DskipTests=true'

      - run:
          command: 'mvn install -f ./fd-common/pom.xml '

      - save_cache:
          paths:
            - ~/.m2
          key: org-flockdata-v2a-{{ checksum "pom.xml" }}

      - store_test_results:
          path: ./target/test-results

      - store_artifacts:
          path: fd-common/target/*.jar

  build-client:
    machine:
      enabled: true
    environment:
      _JAVA_OPTIONS: "-Xms256m -Xmx512m"
    working_directory: '~/org.flockdata'

    steps:
      - restore_cache:
            key: org-flockdata-src-repo-{{ .Environment.CIRCLE_SHA1 }}

      - restore_cache:
            key: org-flockdata-v2a-{{ checksum "pom.xml" }}

      - run:
          command: 'mvn -q test -f fd-client/pom.xml'

      - store_test_results:
          path: fd-client/target/test-results

      - store_artifacts:
          path: fd-client/target/*.jar

  build-security:
    machine:
      enabled: true
    environment:
      _JAVA_OPTIONS: "-Xms256m -Xmx512m"
    working_directory: '~/org.flockdata'

    steps:
      - restore_cache:
            key: org-flockdata-src-repo-{{ .Environment.CIRCLE_SHA1 }}

      - restore_cache:
            key: org-flockdata-v2a-{{ checksum "pom.xml" }}

      - run:
          command: 'mvn -q test -f fd-security/pom.xml'

      - save_cache:
          paths:
            - ~/.m2
          key: org-flockdata-v2a-{{ checksum "pom.xml" }}

      - store_test_results:
          path: fd-security/target/test-results

      - store_artifacts:
          path: fd-security/target/*.jar

  build-search:
    machine:
      enabled: true
    environment:
      _JAVA_OPTIONS: "-Xms256m -Xmx512m"
    working_directory: '~/org.flockdata'

    steps:
      - restore_cache:
            key: org-flockdata-src-repo-{{ .Environment.CIRCLE_SHA1 }}

      - restore_cache:
            key: org-flockdata-v2a-{{ checksum "pom.xml" }}

      - run:
          command: 'pushd fd-search && mvn -q install && popd'

      - store_test_results:
          path: fd-search/target/test-results

      - store_artifacts:
          path: fd-search/target/*.jar

  build-graph:
    machine:
      enabled: true
    environment:
      _JAVA_OPTIONS: "-Xms256m -Xmx512m"
    working_directory: '~/org.flockdata'

    steps:
      - restore_cache:
            key: org-flockdata-src-repo-{{ .Environment.CIRCLE_SHA1 }}

      - restore_cache:
            key: org-flockdata-v2a-{{ checksum "pom.xml" }}

      - run:
          command: 'mvn -q test -f fd-graph/pom.xml'

      - store_test_results:
          path: fd-graph/target/test-results

      - store_artifacts:
          path: fd-graph/target/*.jar

  build-store:
    machine:
      enabled: true
    environment:
      _JAVA_OPTIONS: "-Xms256m -Xmx512m"
    working_directory: '~/org.flockdata'

    steps:
      - restore_cache:
            key: org-flockdata-src-repo-{{ .Environment.CIRCLE_SHA1 }}

      - restore_cache:
            key: org-flockdata-v2a-{{ checksum "pom.xml" }}

      - run:
          command: 'mvn -q install -f fd-store/pom.xml'

      - store_test_results:
          path: fd-store/target/test-results

      - store_artifacts:
          path: fd-store/target/*.jar

  build-batch:
    machine:
      enabled: true
    environment:
      _JAVA_OPTIONS: "-Xms256m -Xmx512m"
    working_directory: '~/org.flockdata'

    steps:
      - restore_cache:
            key: org-flockdata-src-repo-{{ .Environment.CIRCLE_SHA1 }}

      - restore_cache:
            key: org-flockdata-v2a-{{ checksum "pom.xml" }}

      - run:
          command: 'mvn -q test -f fd-batch/pom.xml'

      - store_test_results:
          path: fd-batch/target/test-results

      - store_artifacts:
          path: fd-batch/target/*.jar

  build-shell:
    machine:
      enabled: true
    environment:
      _JAVA_OPTIONS: "-Xms256m -Xmx512m"
    working_directory: '~/org.flockdata'

    steps:
      - restore_cache:
            key: org-flockdata-src-repo-{{ .Environment.CIRCLE_SHA1 }}

      - restore_cache:
            key: org-flockdata-v2a-{{ checksum "pom.xml" }}

      - run:
          command: 'mvn -q install -f fd-shell/pom.xml'

      - store_test_results:
          path: fd-shell/target/test-results

      - store_artifacts:
          path: fd-shell/target/*.jar

  build-engine:
    machine:
      enabled: true
    environment:
      _JAVA_OPTIONS: "-Xms256m -Xmx512m"
    working_directory: '~/org.flockdata'

    steps:
      - restore_cache:
            key: org-flockdata-src-repo-{{ .Environment.CIRCLE_SHA1 }}

      - restore_cache:
            key: org-flockdata-v2a-{{ checksum "pom.xml" }}

      - run:
          command: 'mvn -q install -f fd-engine/pom.xml'

      - save_cache:
          paths:
            - ~/.m2
          key: org-flockdata-v2a-{{ checksum "pom.xml" }}

      - store_test_results:
          path: fd-engine/target/test-results

      - store_artifacts:
          path: fd-engine/target/*.jar

  stage-tests:
    machine:
      enabled: true
    environment:
      _JAVA_OPTIONS: "-Xms256m -Xmx512m"
    working_directory: '~/org.flockdata'

    steps:
      - restore_cache:
            key: org-flockdata-src-repo-{{ .Environment.CIRCLE_SHA1 }}

      - restore_cache:
            key: org-flockdata-v2a-{{ checksum "pom.xml" }}

      - run:
          command: 'mvn -q package -P docker -DskipTests'

      - run:
          command: 'pushd fd-docker-staging && mvn -q verify -P integration && popd'

      - save_cache:
          paths:
            - ~/.m2
          key: org-flockdata-v2a-{{ checksum "pom.xml" }}

      - store_test_results:
          path: fd-docker-staging/target/test-results


workflows:
  version: 2
  build_and_stage:
    jobs:
      - checkout-code
      - build-common:
          requires:
            - checkout-code
      - build-security:
          requires:
            - build-common
      - build-client:
          requires:
            - build-security
      - build-batch:
          requires:
            - build-client
      - build-shell:
          requires:
            - build-client
      - build-engine:
          requires:
            - build-client
      - build-graph:
          requires:
            - build-security
      - build-search:
          requires:
            - build-security
      - build-store:
          requires:
            - build-security
      - stage-tests:
          requires:
            - build-store
            - build-search
            - build-engine
            - build-graph
#      - deploy:
#          requires:
#            - stage-tests
#          filters:
#            branches:
#              only: /release.*/


#deployment:
#  snapshot:
#    branch: /snapshot.*/
#    commands:
#      - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
#      - docker push flockdata/fd-engine
#      - docker push flockdata/fd-store
#      - docker push flockdata/fd-search
#      - docker push flockdata/fd-client
#
#  release:
#    branch: /release.*/
#    commands:
#      - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
#      - docker push flockdata/fd-engine
#      - docker push flockdata/fd-store
#      - docker push flockdata/fd-search
#      - docker push flockdata/fd-client

