# Default configuration properties for fd-engine


server:
  port: 8082

application:
  title: FlockData StoreWriter

eureka:
  client:
    serviceUrl:
      defaultZone: ${org.fd.discovery.url:http://127.0.0.1:8761/eureka/}
    enabled: 'false'

spring:
  application:
    name: fd-store
  profiles:
    active: fd-no-auth,riak
    include: fd-server
  cloud:
    config:
      discovery:
        enabled: false
  messages:
    encoding: UTF-8
  http:
    encoding:
      charset: UTF-8 # the encoding of HTTP requests/responses
      enabled: 'true' # enable http encoding support
      force: 'true' # force the configured encoding

org.fd:
  store:
    system:
      enabled: true # Service is accepting requests
      engine: RIAK # Default store engine to use
      api: api # Mount point for the API end-points

    executor:
      poolSize: 8-15
      queueCapacity: 3
    messaging:
      exchange: fd.store.exchange
      binding: fd.store.binding
      queue: fd.store.queue
      concurrentConsumers: 2
      prefetchCount: 1

  search:
    api: http://localhost:8081

riak:
  hosts: 127.0.0.1
  mapurl: http://localhost:8098/mapred

rabbit:
  port: 5672
  host: localhost



