# Default configuration properties for fd-engine


server:
  port: 14003

application:
  title: FlockData StoreWriter

eureka:
  client:
    healthcheck:
      enabled: false
    serviceUrl:
      defaultZone: ${org.fd.discovery.url:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true

#    enabled: false

spring:
  application:
    name: fd-store
  profiles:
#    Switch memstore to something like riak when you're needs are more persistent
    active: memstore
    include: fd-server,fd-no-auth
#  Run with the "discovery" profile active to connect
#  cloud:
#    discovery:
#      enabled: false
  messages:
    encoding: UTF-8
  rabbitmq:
    password: guest
    username: guest
    host: localhost
    port: 5672
    virtual-host: /

logging:
  level:
    org.flockdata.client: debug
    org.springframework: error
    org.flockdata: info

org.fd:
  store:
    system:
      enabled: true # Service is accepting requests
      engine: RIAK # Default store engine to use
      api: api # Mount point for the API end-points

    executor:
      poolSize: 8-15
      queueCapacity: 3
    messaging:
      concurrentConsumers: 2
      prefetchCount: 1

  search:
    api: http://localhost:8081

riak:
  hosts: 127.0.0.1
  mapurl: http://localhost:8098/mapred




