
server:
  port: 9099

spring:
  profiles:
    active: production
    # include: fd-batch  #Enable this if you want spring batch support in your project

#Thu Mar 03 08:41:03 NZDT 2016
org.fd:
  client:
    # The API key is used to identify a user associated with the company.
    # You can get your APIKey via Curl with the following command
    # curl -u mike http://localhost:8080/api/v1/profiles/me
    apikey: xi7xBfLJSGmQzAMQbq4U0w
    http:
      user: mike
      pass: 123
    batchsize: 1
    login:
      user: mike
    default:
      company: FlockData
  track:
    messaging:
      binding: fd.track.binding
      queue: fd.track.queue
      exchange: fd.track.exchange
  engine:
    api: http://chm-dev-fds:8080/api

rabbit:
  pass: guest
  user: guest
  host: chm-dev-fds
  persistent: true

