
#Random port as, by default, this just starts and shuts down
server:
  port: 0

spring:
  profiles:
    active: fd-server
    # include: fd-batch  #Enable this if you want spring batch support in your project

org.fd:
  client:
    # The API key is used to identify a user associated with the company.
    # You can get your APIKey via Curl with the following command
    # curl -u mike http://localhost:8080/api/v1/profiles/me

    # Either set in in your config file or pass it as a command line parameter
    # --org.fd.client.apikey=SDKMcCU_TRCh7fL09PoFUg
    # apikey: SDKMcCU_TRCh7fL09PoFUg
    batchsize: 1
    login:
      user: demo
    default:
      company: FlockData
  track:
    messaging:
      binding: fd.track.binding
      queue: fd.track.queue
      exchange: fd.track.exchange
  engine:
    api: http://localhost:8080

rabbit:
  pass: guest
  user: guest
  host: localhost
  persistent: true

