version: '2'
services:
  rabbit:
      container_name: rabbit
      image: rabbitmq:3-management
      ports:
        - '5672:5672'
        - '15672:15672'

  riak:
      container_name: riak
      image: lapax/riak:latest
      ports:
        - '8087:8087'

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:1.7.5
    command: elasticsearch -Des.cluster.name=es_flockdata
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      ES_NODE_NAME: 'TestNode'

  fd-engine:
    container_name: fd-engine
    image: flockdata/fd-engine:latest

    ports:
      - '8080:8080'
      - '7474:7474'

    environment:
      spring.cloud.config.discovery.enabled: 'false'
      eureka.instance.nonSecurePort: 8080
      eureka.client.enabled: 'false'
      server.port: 8080
      spring.profiles.active: production
      spring.profiles.include: fd-auth-test

      rabbit.host: rabbit
      org.fd.search.api: http://fd-search:8081
      org.fd.store.api: http://fd-store:8082
      org.neo4j.path: /opt/flockdata
      org.neo4j.server.database.location: /opt/flockdata/data/neo4j

    depends_on:
      - rabbit
      - eureka
    links:
      - fd-search
      - rabbit
      - eureka

  fd-search:
    container_name: fd-search
    image: flockdata/fd-search:latest
    ports:
     - '8081:8081'
     - '9201:9201'
     - '9301:9301'
    depends_on:
      - rabbit
      - eureka
      - elasticsearch

    environment:
      spring.cloud.config.discovery.enabled: 'false'
      eureka.instance.nonSecurePort: 8081
      eureka.client.enabled: 'false'
      server.port: 8081
      rabbit.host: rabbit
      org.fd.engine.url: 'http://fd-engine:8080'
      riak.hosts: riak

      # Enables integration functionality
      spring.profiles.active: production
      spring.profiles.include: fd-auth-test

      es.http.port: 9201
      es.tcp.port: 9301
      es.clustername: 'es_flockdata'
      es.path.home: /opt/flockdata
      es.path.data: /opt/flockdata/data

  fd-store:
    container_name: fd-store
    image: flockdata/fd-store:latest
    ports:
     - '8082:8082'
    depends_on:
      - rabbit
      - eureka
      - riak
    environment:
      server.port: 8082
      rabbit.host: rabbit
      spring.cloud.config.discovery.enabled: 'false'
      eureka.client.enabled: 'false'
      eureka.instance.nonSecurePort: 8082

      # Enables integration functionality
      spring.profiles.active: production
      spring.profiles.include: fd-auth-test,riak
      riak.hosts: riak
      es.clustername: 'es_flockdata'


networks:
  default:
    # Use the overlay driver for multi-host communication
    driver: bridge
